# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import json

# Import API key
from api_keys import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

# Hide warning messages in notebook
import warnings
warnings.filterwarnings('ignore')

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
weather_df = pd.read_csv('../WeatherPy/city_weather.csv')
weather_df = weather_df.drop(columns = 'Unnamed: 0')
weather_df.head()

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,meulaboh,11.0,ID,1.570336e+09,78.0,4.14,96.13,78.28,6.71
1,barrow,31.0,AR,1.570336e+09,88.0,-38.31,-60.23,39.62,5.66
2,nhulunbuy,40.0,AU,1.570336e+09,55.0,-12.18,136.78,86.00,12.75
3,lesnyye polyany,90.0,RU,1.570336e+09,86.0,55.97,37.87,39.20,8.95
4,ronne,90.0,FR,1.570336e+09,100.0,48.45,0.83,55.40,6.93

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
# Store latitude, longitude, and weights
locations = weather_df[['Lat', 'Lng']].astype(float)
humidity = weather_df['Humidity'].astype(float)

In [4]:
# Plot Heatmap
fig = gmaps.figure()

heat_layer = gmaps.heatmap_layer(locations, weights = humidity,
                                 dissipating=False, max_intensity=150,
                                 point_radius = 3
)

fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.
##### Criteria:
* A max temperature lower than 80 degrees but higher than 70.
* Wind speed less than 10 mph.
* Cloudiness less than 0.

In [5]:
# filtering the data based on the criteria above
filter_df = weather_df.loc[
    ((weather_df['Max Temp'] < 80) & (weather_df['Max Temp'] > 70) 
     & (weather_df['Wind Speed'] < 10) & (weather_df['Cloudiness'] == 0)), :
]
filter_df.head()

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
70,gulabpura,0.0,IN,1.570336e+09,55.0,25.91,74.66,78.97,5.31
99,saquarema,0.0,BR,1.570336e+09,94.0,-22.93,-42.51,77.00,2.24
140,iranshahr,0.0,IR,1.570336e+09,69.0,27.21,60.69,73.40,4.70
168,nova vicosa,0.0,BR,1.570336e+09,85.0,-17.89,-39.37,73.10,8.80
179,ambilobe,0.0,MG,1.570336e+09,81.0,-13.19,49.05,73.32,7.59

In [6]:
# only 15 candidates left
len(filter_df)

15

### Hotel Map
* Store into variable named `filter_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [7]:
# add the needed variables' columns
filter_df["hotel_lat"] = ""
filter_df["hotel_lng"] = ""
filter_df["hotel_name"] = ""
filter_df.head()

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed,hotel_lat,hotel_lng,hotel_name
70,gulabpura,0.0,IN,1.570336e+09,55.0,25.91,74.66,78.97,5.31,,,
99,saquarema,0.0,BR,1.570336e+09,94.0,-22.93,-42.51,77.00,2.24,,,
140,iranshahr,0.0,IR,1.570336e+09,69.0,27.21,60.69,73.40,4.70,,,
168,nova vicosa,0.0,BR,1.570336e+09,85.0,-17.89,-39.37,73.10,8.80,,,
179,ambilobe,0.0,MG,1.570336e+09,81.0,-13.19,49.05,73.32,7.59,,,

In [8]:
# loop through the googleplace API to get the needed variables

url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

# use iterrows to iterate through pandas dataframe
for index, row in filter_df.iterrows():

    # get city name from df
    city = row['City']
    
    # geocoordinates
    target_coordinates = f"{row['Lat']}, {row['Lng']}"
    target_radius = 5000
    target_type = "hotel"
    
    # set up a parameters dictionary
    params = {
        "location": target_coordinates,
        "radius": target_radius,
        "type": target_type,
        "key": g_key
    }

    # assemble url and make API request
    print(f"Retrieving Results for Index {index}: {city}.")
    response = requests.get(url, params=params).json()
    
    try:
        filter_df.loc[index, 'hotel_lat'] = response["results"][0]["geometry"]["location"]['lat']
        filter_df.loc[index, 'hotel_lng'] = response["results"][0]["geometry"]["location"]['lng']
        filter_df.loc[index, 'hotel_name'] = response["results"][0]["name"]
        
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")
        
    print("------------")

Retrieving Results for Index 70: gulabpura.
------------
Retrieving Results for Index 99: saquarema.
------------
Retrieving Results for Index 140: iranshahr.
------------
Retrieving Results for Index 168: nova vicosa.
------------
Retrieving Results for Index 179: ambilobe.
------------
Retrieving Results for Index 209: caravelas.
------------
Retrieving Results for Index 238: riyadh.
------------
Retrieving Results for Index 315: chittaurgarh.
------------
Retrieving Results for Index 354: nizwa.
------------
Retrieving Results for Index 371: cayenne.
------------
Retrieving Results for Index 386: buraydah.
------------
Retrieving Results for Index 430: bafq.
------------
Retrieving Results for Index 531: mocuba.
------------
Retrieving Results for Index 553: iquitos.
------------
Retrieving Results for Index 559: rodrigues alves.
------------

In [9]:
# check dataframe
filter_df.head()

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed,hotel_lat,hotel_lng,hotel_name
70,gulabpura,0.0,IN,1.570336e+09,55.0,25.91,74.66,78.97,5.31,25.9023,74.6881,Hurda
99,saquarema,0.0,BR,1.570336e+09,94.0,-22.93,-42.51,77.00,2.24,-22.9324,-42.4867,Saquarema
140,iranshahr,0.0,IR,1.570336e+09,69.0,27.21,60.69,73.40,4.70,27.2012,60.6866,Iranshahr
168,nova vicosa,0.0,BR,1.570336e+09,85.0,-17.89,-39.37,73.10,8.80,-17.9009,-39.3717,Nova Viçosa
179,ambilobe,0.0,MG,1.570336e+09,81.0,-13.19,49.05,73.32,7.59,-13.2026,49.0514,Ambilobe

In [10]:
# I didn't use the code given, because I think using the city coordinates as the marker of hotel is a less intuitive than
# using the actual hotel's coordinates.

# Applying this thought to build the marker layer

info_box_template = """
<dl>
<dt>Name</dt><dd>{hotel_name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
hotel_info = [info_box_template.format(**row) for index, row in filter_df.iterrows()]
locations = filter_df[['hotel_lat', 'hotel_lng']]

In [11]:
# Add marker layer ontop of heat map
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# Display Map
fig

Figure(layout=FigureLayout(height='420px'))